# This Policy forward each call to the "external_authz" endpoint registered
# in ISTIO. If this endpoints returns an HTTP 403 (deny), the call is rejected via RBAC and
# the user sees an "unauthenticated" in the browser.
# If the Policy returns an HTTP 200 (allow), the normal ISTIO check via filter starts.
#
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: backend-auth-oidc
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  action: CUSTOM
  provider:
    # The provider name must match the extension provider defined in the mesh config.
    name: oidc-http
  rules:
    - to:
        - operation:
            hosts: ["app.<DOMAIN>"]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: backend-auth-defaultallow
  namespace: istio-system
spec:
  selector:
    matchLabels:
      istio: ingressgateway
  action: ALLOW
  rules:
  - {}